apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: website
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: website
        tier: backend
    spec:
      containers:
      - name: backend
        image: website-backend
        env:
        - name: DATABASE_URL
          value: "postgresql://niv:niv123@db-service:5432/mydb"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
