apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: website
      tier: db
  replicas: 1
  template:
    metadata:
      labels:
        app: website
        tier: db
    spec:
      containers:
      - name: db
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "niv"
        - name: POSTGRES_PASSWORD
          value: "niv123"
        - name: POSTGRES_DB
          value: "mydb"
