FROM node:23.1.0-bookworm-slim AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

#builds the static files to run the application
RUN npm run build

#makes the static files accessable over http
#RUN npm install -g serve

##########################################################
FROM node:23.1.0-alpine

WORKDIR /app

#RUN mkdir -p /app/build

COPY --from=build /app/build /app/build

EXPOSE 3000

CMD ["npx", "serve", "-s", "build"]
