apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: website
    tier: backend
spec:
  selector:
    app: website
    tier: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
