apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: website
    tier: frontend
spec:
  selector:
    app: website
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
